baseURL: https://john-purcell.netlify.app/
languageCode: en-us
title: John Purcell - Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: #-
      Part time farmer,
      full time charmer
    title: John Purcell
  blog: {}
  contact:
    address:
      - city: Cashel
        country: Ireland
        street: Ballinree
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jpurcell.mfa2022@london.edu
        title: JP
    enable: yes
    phone:
      - phone: (+353) 87-151-2513 x1234
        title: Mobile
  custom_css: []
  custom_js: []
  description: JP's website
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: John Purcell
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/johndpurcell/
      - icon: fa-github
        label: GitHub
        url: https://github.com/JP-98
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/john-purcell-6b611216b/
  image: ''
  name: John Purcell
  navigation:
    button1:
      - name: Home
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Background
        url: post/me
      - name: Python
        url: blogs/Options
      - name: Julia
        url: blogs/Julia
      - name: Resume
        url: blogs/CV
    menu: Menu
    subtitle: By HTML5 Up
    title: Refresh
  tiles:
    enable: yes
    showcase:
      - image: fish.jpg
        subtitle: Immature, Arrogant, but Undoubtedly Brilliant
        title: Introduction
        url: post/me
      - image: frmclass.jpg
        subtitle: The Isle of Saints and Scholars
        title: Ireland in Colour
        url: blogs/Ireland
      - image: italy.jpg
        subtitle: Todo el Mundo
        title: Travel
        url: blogs/Travel
      - image: flux.jpg
        subtitle: Using Julia's Flux Package to Train a Neural Network Model
        title: Training a Stacked Ensemble of Supervised Models to Predict Stock Return Directions
        url: blogs/Julia
      - image: work.jpeg
        subtitle: Better than Shorting the Vix
        title: Exploiting Implied Volatility Deviations from Realised using Options  
        url: blogs/Options
      - image: ff.jpg
        subtitle: 
        title: Curriculum Vitae
        url: blogs/CV

  two:
    buttonText: Get Started
    enable: yes
    subtitle: "*** Faigheann cos ar siúl rud nach bhfaigheann cos ina cónaí ***"
    title: Dive In
    url: '#'
