baseURL: https://john-purcell.netlify.app/
languageCode: en-us
title: John Purcell - Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: #-
      Part time Farmer,
      Full time Charmer
    title: John Purcell
  blog: {}
  contact:
    address:
      - city: Cashel
        country: Ireland
        street: Ballinree
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jpurcell.mfa2022@london.edu
        title: JP
    enable: yes
    phone:
      - phone: (+353) 151-2513 x1234
        title: Mobile
  custom_css: []
  custom_js: []
  description: JP's website
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: John Purcell
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/johndpurcell/
      - icon: fa-github
        label: GitHub
        url: https://github.com/JP-98
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/john-purcell-6b611216b/
  image: 'IMG-20190914-WA0001'
  name: John Purcell
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Background
        url: post/me
      - name: '#'
        url: '#'
      - name: '#'
        url: '#'
    menu: Menu
    subtitle: By HTML5 Up
    title: Refresh
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: '#'
        title: Introduction
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Portfolio
        title: All things Coding 
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: The Isle of Saints and Scholars
        title: Ireland in Colour
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Todo el Mundo
        title: Travel
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Better than Shorting the Vix
        title: Exploiting Implied Volatility Overpricing using Options  
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Nothing New Here
        title: Fama MacBeth Two Pass Regression: Have FF Factors Become Obsolete?
        url: blogs/ipsum
      - image: pic07.jpg
        subtitle: Using Julia's Flux Package to Train a Neural Network Model
        title: Training a Stacked Ensemble of Supervised Models to Predict Stock Return Directions
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
