baseURL: https://john-purcell.netlify.app/
languageCode: en-us
title: John Purcell - Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: #-
      Part time Farmer,
      Full time Charmer
    title: John Purcell
  blog: {}
  contact:
    address:
      - city: Cashel
        country: Ireland
        street: Ballinree
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jpurcell.mfa2022@london.edu
        title: JP
    enable: yes
    phone:
      - phone: (+353) 151-2513 x1234
        title: Mobile
  custom_css: []
  custom_js: []
  description: JP's website
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: John Purcell
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/johndpurcell/
      - icon: fa-github
        label: GitHub
        url: https://github.com/JP-98
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/john-purcell-6b611216b/
  image: 'IMG-20190914-WA0001'
  name: John Purcell
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Background
        url: post/me
      - name: Portfolio
        url: post/Portfolio
    menu: Menu
    subtitle: By HTML5 Up
    title: Refresh
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Life and Learnings
        title: Introduction
        url: post/me
      - image: pic02.jpg
        subtitle: The Isle of Saints and Scholars
        title: Ireland in Colour
        url: post/me
      - image: pic03.jpg
        subtitle: Todo el Mundo
        title: Travel
        url: post/me
      - image: pic04.jpg
        subtitle: Using Julia's Flux Package to Train a Neural Network Model
        title: Training a Stacked Ensemble of Supervised Models to Predict Stock Return Directions
        url: Portfolio/Julia
      - image: pic05.jpg
        subtitle: Better than Shorting the Vix
        title: Exploiting Implied Volatility Overpricing using Options  
        url: Portfolio/Options
      - image: pic06.jpg
        subtitle: Nothing New Here
        title: Fama MacBeth Two Pass Regression: Have FF Factors Become Obsolete?
        url: Portfolio/Fama-MacBeth

  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Necessity is the mother of invention, while curiosity is her grandmother"
    title: Immerse Yourself
    url: blogs
